### ISSUE TITLE
Add ability to get post analysis sets directly from external source

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#82] opened 2015-04-23 19:31 UTC
Add ability to create signature sets from external sources via webservices.  Instead of only having the option of the user supplying the signature sets create signature sets on the fly from database like
 opossum for transcription factor targets.
directly from http://download.baderlab.org/EM_Genesets/current_release/ - make a new directory which contain all of our geneset collection that can be used for post analysis (TFs, mir targets, drug targets, phenotypes)

**Comment by mikekucera** [comment] 2017-12-11 22:46
Fixed along with #288, in fact #288 is a duplicate of this one.

**Closed as completed by mikekucera** 2017-12-11 22:46 UTC
Labels: enhancement, PostAnalaysis
