### ISSUE TITLE
Single Cell: Enrichment panel is reset (blank) after saving and reloading EM 

### ISSUE THREAD

**Issue by s2hui** [BaderLab/EnrichmentMapApp#431] opened 2020-11-03 14:55 UTC
Hi, 
I am running EM 3.3.1 (cytoscape versions 3.8.1. and 3.8.2). 
After I create an enrichment map and save it as a Cytoscape session, when I reload it, the network is there but the EM Panel is blank. The associated input files (expression, enrichments, GMT files) are gone and there is no way to adjust the FDRs, edge similarities or other parameters.

shirley

**Comment by mikekucera** [comment] 2020-11-06 15:21
The following exception is in the log when trying to save the session file. 

```
Caused by: java.lang.OutOfMemoryError
	at java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:214) ~[?:?]
	at java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:206) ~[?:?]
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:173) ~[?:?]
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538) ~[?:?]
	at java.lang.StringBuffer.append(StringBuffer.java:312) ~[?:?]
	at java.io.StringWriter.write(StringWriter.java:106) ~[?:?]
	at java.io.StringWriter.append(StringWriter.java:150) ~[?:?]
	at java.io.StringWriter.append(StringWriter.java:41) ~[?:?]
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:534) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapters$12.write(TypeAdapters.java:343) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapters$12.write(TypeAdapters.java:332) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:93) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[?:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[?:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[?:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[?:?]
	at com.google.gson.Gson.toJson(Gson.java:669) ~[?:?]
	at com.google.gson.Gson.toJson(Gson.java:648) ~[?:?]
	at com.google.gson.Gson.toJson(Gson.java:603) ~[?:?]
	at com.google.gson.Gson.toJson(Gson.java:583) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.model.io.ModelSerializer.serialize(ModelSerializer.java:54) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.model.io.ModelSerializer.serialize(ModelSerializer.java:38) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.model.io.SessionModelIO.lambda$saveModel$0(SessionModelIO.java:89) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.model.io.SessionModelIO.saveModel(SessionModelIO.java:86) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.model.io.SessionListener.save(SessionListener.java:64) ~[?:?]
	at org.baderlab.csplugins.enrichmentmap.model.io.SessionListener.handleEvent(SessionListener.java:47) ~[?:?]

```

**Comment by risserlin** [comment] 2020-11-06 15:23
@s2hui that is probably because of the huge single cell expression file that you were using.  Was it helpful loading the original expression file into EM?

**Comment by s2hui** [comment] 2020-11-06 16:14
@risserlin yes it's nice to be able to view the expression file with the network.  unfortunately I think very large data sets is going to be the norm for single cell data (i.e. huge data sets, 10s of thousands of cells by 10s of thousands of genes).

**Comment by s2hui** [comment] 2020-11-06 16:50
Now that I think of It more, it not be easily interpretable to actually to view the entire single gene expression file.  I actually end up collapsing all the values using the compress dropdown box.  I wonder if I can just upload a mean expression file...rather than the entire thing...

**Comment by mikekucera** [comment] 2020-11-06 19:01
Yes its being caused by huge expression files. It is possible to change how expression data is saved to the session in order to avoid the OutOfMemoryError, but that's a pretty big change, and it wouldn't be backwards compatible with the current or previous versions of EM.

**Comment by mikekucera** [comment] 2020-11-13 20:59
Perhaps we should add special support for single cell data, depending on how common this type of analysis is (ie how many users would use it). We could add an option to collapse the expression values on load, that way only one column of expressions per data set would be stored. Are there other ways we could collapse the data that would be useful? Gary mentioned something about taking a random subsample, but I'm not entirely sure what that entails.

**Comment by s2hui** [comment] 2020-11-13 23:56
single cell is becoming/is very popular nowadays and I think it would be
great to fully support this type of data.
I think it will be hard to find one metric that will be ideal for
collapsing all the data.  Currently I was thinking of precomputing the
means and loading just one column in per data set as you described.
The current metrics mean, max, min would still be useful for single cell.
I am guessing Gary means to take a random subsample of the cells per data
set to represent in the heatmap.  So each data set would show x randomly
sampled columns from that data set?
I can think of this some more and also ask some other people what they
think...
shirley

**Comment by mikekucera** [comment] 2020-11-16 15:49
I think it would be great to add support for single cell to EM.
We could store min, max and mean for each data set, and allow the user to switch between just those.

**Comment by mikekucera** [comment] 2022-11-08 15:07
Looks like the OutOfMemoryError is a duplicate of bug #482, which is now fixed, so this should be fixed as well.

**Closed as completed by mikekucera** 2022-11-08 15:07 UTC
