### ISSUE TITLE
NullPointer when saving second session with EnrichmentMap

### ISSUE THREAD

**Issue by krassowski** [BaderLab/EnrichmentMapApp#324] opened 2018-02-27 13:36 UTC
When saving a session in Cytoscape with an enrichment map I noticed a troubling error messages generated by Cytoscape. I would like to share my observations with you and ask if I should be worried about integrity of my session save files when I see such errors.

The error happens after saving a new session but only if this is not a first session since the start of the app. The error does not happen with some datasets, but happens with others.

Here is a minimal reproducible example:

Let's say I have a file named `test.sh` with the following content: 

```bash
H='Content-Type: application/json'
CWD='/home/krassowski/test_cytoscape'
URL='http://localhost:1234/v1/commands'
wget -S -qO- --header "$H" --post-data '{}' "$URL/session/new"
wget -S -qO- "$URL/enrichmentmap/build?analysisType=generic&gmtFile=$CWD/gene_sets.gmt&enrichmentsDataset1=$CWD/terms.txt"
wget -S -qO- --header "$H" --post-data "{file: \"$CWD/test.cys\"}" "$URL/session/save as"
```

I start my Cytoscape app with:
```bash
/home/krassowski/Cytoscape_v3.6.0/cytoscape.sh -R 1234
```
and after waiting for it to be ready I execute the test.sh twice:

```bash
./test.sh
./test.sh
```

And the second execution produces following errors:

```java
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:120)
	at org.cytoscape.event.internal.CyEventHelperImpl.fireEvent(CyEventHelperImpl.java:79)
	at org.cytoscape.session.internal.CySessionManagerImpl.getCurrentSession(CySessionManagerImpl.java:104)
	at org.cytoscape.task.internal.session.SaveSessionAsTask.run(SaveSessionAsTask.java:75)
	at org.cytoscape.command.internal.TFExecutor.execute(TFExecutor.java:91)
	at org.cytoscape.command.internal.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:175)
	at org.cytoscape.command.internal.CommandExecutorTask.run(CommandExecutorTask.java:54)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.executeCommand(CommandResource.java:357)
	at org.cytoscape.rest.internal.commands.resources.CommandResource.handleJSONCommand(CommandResource.java:261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:366)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.baderlab.csplugins.enrichmentmap.view.control.ControlPanelMediator.lambda$getAllViewParams$13(ControlPanelMediator.java:263)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.baderlab.csplugins.enrichmentmap.view.control.ControlPanelMediator.getAllViewParams(ControlPanelMediator.java:248)
	at org.baderlab.csplugins.enrichmentmap.view.control.io.SessionViewIO.saveView(SessionViewIO.java:56)
	at org.baderlab.csplugins.enrichmentmap.model.io.SessionListener.save(SessionListener.java:66)
	at org.baderlab.csplugins.enrichmentmap.model.io.SessionListener.handleEvent(SessionListener.java:47)
	... 66 more

```

Here is a minimal `terms.txt` file:

```
term.id	term.name	p.val
REAC:1474244	Extracellular matrix organization	0.000252318365920905
```

and `gene_sets.gmt`:
```
REAC:1474244	Extracellular matrix organization	MMP16	COL8A2	COL1A1	MMP10	COL20A1	CAPN14	COL18A1	COMP	COL11A2	CAPN11	KLKB1	COL16A1	MMP19	TGFB2	SPP1	ITGAL	PLOD1	LAMA3	AC005338.1ITGAX	P3H1	MATN3	DCN	COL24A1	TNN	MMP9	ICAM1	TNC	HSPG2	LAMA5	PRSS1	MADCAM1	FURIN	LOXL4	DSPP	MMP25	CAPNS2	CAPN9	ITGB3	MMP1	KDR	MMP20	LTBP1	P3H3	FGB	FBN2	FMOD	MATN4	TPSAB1	PLOD2	ITGA6	CAPN1	LAMC1	COL26A1	ITGA2	ITGB4	DDR2	CTSL	COL3A1	ADAMTS3	COL9A3	TGFB1	CAPN8	TLL1	BSG	COL22A1	ITGA9	LAMA2	COL25A1	PTPRS	CTSG	MMP3	CEACAM1	ITGAE	ITGB7	COL17A1	DMD	COL27A1	ICAM5	ITGA8	LAMB1	DAG1	ADAM9	COL6A1	CRTAP	SPARC	CTRB2	ITGAD	CMA1	TMPRSS6	MFAP5	ITGAV	ITGA5	P4HA2	NID1	CTRB1	MMP15	CD47	ADAMTS2	TTR	ADAM15	PSEN1	A2M	CDH1	CTSS	PLOD3	MATN1	NCSTN	CTSB	FGA	ITGA10	THBS1	FBN3	GDF5	CTSK	SDC2	LRP4	COL5A3	FBLN5	HAPLN1	CTSD	COL10A1	ADAMTS1	VCAN	ADAMTS8	TLL2	LUM	CAPN12	CAPN13	SERPINE1	COL4A5	TIMP2	COL28A1	TIMP1	COL1A2	KLK2	BMP2	MMP13	MUSK	NCAN	COL4A6	ITGA4	MMP8	MFAP4	LTBP2	SPOCK3	MMP12	FBLN1	LOXITGA2B	ICAM3	CEACAM8	EFEMP2	CEACAM6	BMP1	ADAM8	P4HA1	MMP11	VTN	NCAM1	SERPINH1	COL8A1	PDGFB	TRAPPC4	LOXL1	COL6A2	MMP14	PCOLCE2	CAPNS1	FBN1	FGG	COL9A2	HTRA1	ITGA7	COL13A1	AGRN	ITGA1	CD44	FN1	LAMA4	ELANE	COL12A1	CASP3	EFEMP1	TNR	COL6A5	PCOLCE	MMP7	ADAM17	NRXN1	COL7A1	MFAP3	ITGB1	ADAM10	TGFB3	LTBP4	MFAP2	COL21A1	COL14A1	CD151	ITGA3	LAMB3	LOXL3	COL2A1	ITGB5	DMP1	PRSS2	JAM2	PRKCA	ACAN	LTBP3	CAPN3	PECAM1	BGN	BMP10	ADAMTS4	ITGB6	COL4A3	ICAM4	ITGB8	CAPN6	FBLN2	PPIB	ADAMTS9	BMP4	CAPN2	ELNPLEC	ADAMTS16	MFAP1	COL9A1	VCAM1	CTSV	CAPN15	CAPN5	ITGAM	COL11A1	COL4A4	LOXL2	KLK7	SDC4	LAMB2	ACTN1	COL6A3	COLGALT1	ITGB2	LAMC3	ITGA11	COLGALT2	CAPN7	F11R	COL23A1	BMP7	NTN4	CAST	COL6A6	ADAMTS18	FGF2	JAM3	ICAM2	PHYKPL	ASPN	IBSP	MMP2	P4HA3	P3H2	LAMC2	P4HB	SDC3	COL4A1	DDR1	CASK	DST	COL4A2	COL15A1	MMP17	TNXB	CAPN10	ADAMTS5	COL5A1	COL5A2	COL19A1	NID2	BCAN	PDGFA	LAMA1	MMP24	SDC1	ADAMTS14	PLG	
GO:0019221	cytokine-mediated signaling pathway	TXNDC17	DUOX2	SOCS6	IL1B	MAPK3	PSMB7	CSF3	IL20RB	CCL17	IKBKG	TNFRSF17	PODN	PSMC1	FLRT1	ACKR3	SOCS4	PSMA2	TNF	CXCL5	IL17REL	CXCL8	TNFRSF1A	IRF6	ADAR	IRAK1	PLVAP	CCL1	CCL3L3	TNFSF12	LRRC4	PSMB6	TNFRSF11B	LRP8	IFNLR1	TNFRSF18	IFI6	EDA	IFIT2	B2M	ACSL1	GBP1	CD74	KIT	NMI	PSMB5	BAD	CSF1R	MX2	SOCS5	IFNAR1	RTN4RL2	PIAS4	LRRC15	CEACAM1	IL6	PSMB9	IFIT1	THPO	JAK3	F3	CSF1	CX3CR1	IFNA6	IFNA16	PSMB8	TNFRSF1B	NR1H3	IL1RAP	LRRC4B	PSMD7	USP18	SAMHD1	HPX	GPR17	FOXO3	CCR1	IRF2	PSMA6	LRRC19	IL20RA	CDC37	CCR5	RNF31	SUMO1	CTR9	RPS6KA4	PSMC3	IFNA1	CD70	EDN1	NR1H2	STAT6	PSMA1	IL23R	MID1	IFNA10	CAV1	CCL4L2	TNFRSF13C	NLRC5	CAMK2A	PTPN6	IL3	TNFRSF10C	ROBO1	DCN	CAMK2B	AGPAT1	LEPR	PSME2	TRIM26	CIB1	ICAM1	GREM2	AP000295.9	TNFRSF12A	PARK2	TNFRSF6B	HLA-DQA2	SOCS1	STAT3	IRAK3	IL37	CHAD	ZNF675	PSMD6	LTA	CSF2RB	IFNG	CCL16	CISH	PXDN	COMMD7	PLCB1	PF4V1	IRF9	CHUK	WNT5A	TRIM34	ANGPT1	CXCL3	TNFRSF10A	XCL2	EBI3	MED1	TRIM32	TRAF2	IL1F10	PTPN1	MX1	ACKR4	NGFR	HLA-DRA	STAT5B	IRF5	IL2RB	IP6K2	CXCL2	APOA1	PSMB11	ASPN	F2RL1	PSMA8	IL1RL2	IL6R	FCGR1A	LRRTM4	IL31RA	GP1BA	IL22RA2	TNFSF11	CXCR5	IRF1	PRKCD	CARD14	LTB	IL1RN	PSMD2	NR1H4	IRF8	OAS2	HSPA1B	IL36B	TNFRSF10B	ADIPOQ	UBB	IL5RA	PADI2	ECM1	CCL25	CCRL2	PSMC2	TRIM22	CXCL9	JAGN1	CIITA	PSME1	VCAM1	PF4	MPL	STAP1	TRIM5	MST1R	IL7R	CXCL13	UBC	RPS27A	CAMK2G	CREBRF	PODNL1	AXL	TNFRSF4	CD27	MT3	IL12RB1	BGNIFNA2	TNFRSF11A	TRIM25	LSM14A	SHARPIN	IFITM3	HLA-DRB1	TRIM6	IFNAR2	ADAM17	OTULIN	CNTFR	PSMF1	TNFRSF8	IFI35	TXK	IL36G	FLT3	IFNA13	TRAIP	IFITM2	RFFL	XCR1	IFNA5	CXCL11	CLDN18	TNFRSF13B	CASP8	VRK2	IL1A	CD44	MKKS	STAT1	STAT5A	NLRP2B	GAS6	MADD	CCL4	IFNB1	JAK2	OAS1	CCR2	DUOX1	EPOR	TNFRSF21	PSMD11	PSME4	IL17RD	TNFRSF14	TRIM21	SYK	CSF3R	IL6ST	IL1RAPL2	CCL3	IRAK4	CCL14	PSMD5	IL22RA1	CDIP1	CSNK2B	PPBP	TNFAIP3	TNFSF18	PSMD13	IL17RA	IL12B	RBCK1	EGR1	HLA-DPA1	IL15RA	IFNA7	NUMBL	TNFSF13	HIPK1	PSMD1	MAP3K14	TNFRSF9	TRIM62	HLA-G	LRTM1	TRAF6	CLIP3	IFNA4	IL10RB	CD40	TNFSF14	IL13RA1	HSP90AB1	EDN2	IRAK2	IL17RB	CX3CL1	CNTF	EDA2R	CCL5	RELA	IFNGR1	CXCR2	EDAR	CCL7	PSMD9	UBE2K	PSMC5	CPNE1	ADIPOR1	IL12RB2	IFNA14	EDARADD	TYK2	CAMK2D	PTPRN	PSMD12	IL17RE	IFITM1	LRRC66	CXCL12	PML	ZC3H15	SOCS7	SIGIRR	TNFRSF25	TRIM38	CCL22	RIPK2	RELT	PSMA4	TNFSF15	IFNGR2	HLA-DQA1	CACTIN	IRF4	CXCR1	OSM	OASL	SLIT3	JAK1	PSMD4	CD40LG	PTK2B	GPR75	CCL18	PSMB2	IFNE	KRAS	TICAM2	IL9R	BBS4	PALM3	RPS6KA5	CCL11	IL17RC	AIM2	SH2B2	PSMD8	HLA-F	TNFSF4	CCR7	BST2	HIF1A	IL5	PSMB1	CCL2	XCL1	CCL23	FLRT3	HSPA1A	LEP	RTN4RL1	IFNA17	ZCCHC11	FADD	GAB1	PSMC6	KRT18	MYD88	LRRC4C	IL2RG	GBP2	CXCL10	TNFRSF19	PSMB3	PTPN2	IFNA21	AGPAT2	IL21R	SPHK1	TNFRSF10D	PSMA3	SP100	IL4R	PAFAH1B1	CYLD	RSAD2	NOL3	TRIM31	PSMB4	CCL13	HCK	BBS2	SOCS3	PSMD14	TRIM68	IL1R2	MT2A	PSMA5	PSMD10	CCL24	CMKLR1	FCGR1B	CXCL6	IFNA8	RABGEF1	RNASEL	LRRTM3	BIRC2	UBA52	CCL8	PSMC4	CCL21	CCL15	SIRT1	FERHLA-DQB2	CCL26	SMAD4	PYDC1	TAX1BP1	CNOT9	IL13RA2	CEBPA	IL36A	NYX	BIRC3	TREM2	XAF1	TRIM8	HLA-DPB1	RACK1	PSMD3	LRRTM1	PELI3	CXCL1	MUL1	GSTP1	PTAFR	ISG15	FLRT2	HLA-DRB5	LTBR	TRAF1	CCL20	PTPN11	IKBKB	LIFR	PPARG	PSME3	GFI1	PSMB10	PIAS1	TRADD	IFIT3	GHR	IRF7	IL3RA	SLIT2	TRAF3	OAS3	KRT8	FKBP1A	CCR6	SOCS2	PLP2	IL18R1	CLCF1	PSMA7	IL36RN	IL11RA	CCL19	IRF3	HLA-B	ADIPOR2	MAVS	STAT2	IL1R1	IFI30	IFNW1	PYCARD	BAG4	SLC27A1	NCAM1	TNFSF13B	ISG20	ACKR1	EREG	TNIP2	RIPK1	RTN4R	IFNK	OSMR	
REAC:3000157	Laminin interactions	LAMB2	ITGB4	LAMB3	NID1	ITGA3	ITGA7	LAMB1	LAMA4	LAMC3	NID2	ITGB1	LAMA2	ITGA1	LAMC2	COL18A1	ITGAV	ITGA2	LAMA3	LAMC1	LAMA1	LAMA5	HSPG2	ITGA6	
```

**Comment by mikekucera** [comment] 2018-02-27 15:11
Thank you for the detailed bug report.

My suspicion is that the NPE is happening because the session is being saved/loaded very fast because you are using commands. If you add a pause between running the script twice, or add pauses between the wgets, does the NPE go away?

**Comment by krassowski** [comment] 2018-02-27 15:19
Yes, you are right, adding a delay of two seconds (one second was not enough) made the error message go away; I tested with:

```bash
./test.sh
sleep 2
./test.sh
```

**Comment by chrtannus** [comment] 2018-09-18 20:44
I can't reproduce this error anymore on Cytoscape 3.7-SNAPSHOT (tested on macOS and Ubuntu 18). It seems the new version of Cytoscape will fix it.

You can download Cytoscape development snapshots here: http://code.cytoscape.org/jenkins/job/cytoscape-3-gui-distribution/lastSuccessfulBuild/org.cytoscape.distribution$cytoscape/

**Comment by chrtannus** [comment] 2018-09-19 01:03
Please let us know if this issue still happens in Cytoscape 3.7, which will be released soon.

**Closed as completed by chrtannus** 2018-09-19 01:03 UTC
Labels: bug
