### ISSUE TITLE
EM3.2 Table panel : ranking issue

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#366] opened 2019-03-01 21:43 UTC
creating a enrichment map by manually populating the files : GSEA, files used in protocol
it looks like the ranking is in absolute value and does not take the signs into account
-9 8 -7... etc

![screen shot 2019-03-01 at 4 36 30 pm](https://user-images.githubusercontent.com/7570379/53668149-0cfda100-3c41-11e9-9060-6e34a428bec0.png)

![screen shot 2019-03-01 at 4 35 58 pm](https://user-images.githubusercontent.com/7570379/53668161-1a1a9000-3c41-11e9-9aae-1be65651d679.png)

**Comment by mikekucera** [comment] 2019-05-22 20:46
I talked to Veronique about this. I wish I had left a comment on here at the time because my memory is a bit vague. But I think the cause was that its sorting based on the order of the genes in the rank file, which usually works fine. For some reason her rank file was out of order. We agreed that it would be fixed in the rank file as this would be a major change in EnrichmentMap. If that is not satisfactory please reopen this issue.

**Closed as completed by mikekucera** 2019-05-22 20:46 UTC
Labels: bug
