### ISSUE TITLE
EM/g:Profiler 2 datasets

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#158] opened 2016-06-17 18:11 UTC
Can we modify EM/gprofiler such that dataset1 will be red nodes and dataset2 will be  blue nodes (instead of node center, node border) without having to modify the gprofiler output files (currently need to set phenotype to -1  for dataset2 and merge  dataset1 and dataset2 files) ?
- bug detected during the CBW workshop: results in dataset1 and dataset2, no expression files: Heatmap node table and Heatmap edge table were empty.

**Comment by mikekucera** [comment] 2017-10-19 18:49
Duplicate of #270

**Closed as completed by mikekucera** 2017-10-19 18:49 UTC
Labels: duplicate, enhancement
