### ISSUE TITLE
3.1 on Cytoscape 3.6: Node Layout Tools is hiding "Publication ready" and "Set Signature Edge with

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#328] opened 2018-03-26 21:01 UTC
when the node layout tool is displayed, it hides the bottom of the EM panel . There is no scroll bar on EM.
hidden:
![screen shot 2018-03-26 at 4 53 03 pm](https://user-images.githubusercontent.com/7570379/37932696-2b798abc-3117-11e8-80ff-33f1c0d94e39.png)
![screen shot 2018-03-26 at 4 53 15 pm](https://user-images.githubusercontent.com/7570379/37932752-4daaad1e-3117-11e8-9b7c-772fbe2edaf2.png)
hidden part is highlighted:

**Comment by mikekucera** [comment] 2018-03-26 21:21
Duplicate of  #312

**Closed as completed by mikekucera** 2018-03-26 21:21 UTC
