### ISSUE TITLE
Weird radial heatmap colours using NES

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#262] opened 2017-08-03 17:56 UTC
Created multi dataset network.
Specified only use Positive NES values.
Radial heatmap come out like this:

![screen shot 2017-08-03 at 1 55 23 pm](https://user-images.githubusercontent.com/3842763/28935712-713982e6-7853-11e7-9e54-79fcee5db9a9.png)

using NES values:
![screen shot 2017-08-03 at 1 55 56 pm](https://user-images.githubusercontent.com/3842763/28935737-819a89a0-7853-11e7-99cd-7f1905cb1fdc.png)

Here is a link to the session:
https://www.dropbox.com/s/hh5q57ob1qxll7d/weird_radial_heatmap_colors.cys?dl=0

**Comment by risserlin** [comment] 2017-08-29 17:36
this bug is still there in the latest version.  After looking into it, it looks like the weird colors occur when there is no significant NES in the given dataset.

**Comment by mikekucera** [comment] 2017-08-30 19:52
The problem was caused by empty cells in the NES columns. I changed it to use the default color for empty colums, it looks like this... is that ok?
<img width="682" alt="screen shot 2017-08-30 at 3 49 26 pm" src="https://user-images.githubusercontent.com/5350528/29892024-0d95f3f2-8d9b-11e7-8934-033d2ce0d64a.png">

**Comment by risserlin** [comment] 2017-08-30 20:15
Is this change check in to the repo?  It sounds like the right solution but I would like to check it with my current use case.

**Comment by mikekucera** [comment] 2017-08-30 20:39
I just committed it.

**Closed as completed** 2017-09-01 18:58 UTC
Labels: bug, high_priority
