### ISSUE TITLE
EM names in 'Dataset:' don't match network names in "network" panel

### ISSUE THREAD

**Issue by shraddhapai** [BaderLab/EnrichmentMapApp#261] opened 2017-07-21 23:15 UTC
The names given to the maps in the EM panel under 'Data Sets:' is not what the network is called in the 'networks' panel. (This was true even before I exited the original Cytoscape session).
So now I have a 'networks' panel with networks named 'ENrichment Map','Enrichment Map_1', ... 'Enrichment Map_8', and when I click on "Enrichment Map_3", an entry shows up in the 'Data Sets:' panel called "pathways_YES" (which is what I named the EM when I created it).
The name given in the "create new EM" section should automatically become the network name in the "network" panel. It would avoid the user having to name the nets in two places.

**Comment by mikekucera** [comment] 2017-10-18 15:52
This is tricky because there could be multiple data sets so its not clear which one to use as the name. 

I'd like to propose a new field to the EM creation dialog where the user can enter the network name. The field will be auto-populated with the name of the first dataset, which will satisfy most cases. This way the user will clearly see what the network will be named, why its named that way, and gives them an easy way of changing the name up front without having to go to the network panel afterwards.

**Comment by mikekucera** [comment] 2017-10-19 18:46
Duplicate of #223

**Closed as completed** 2017-10-19 18:46 UTC
Labels: duplicate, enhancement
