### ISSUE TITLE
restored session from filtered with slider bars EM has different universe for Post analysis

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#2] opened 2013-12-18 14:54 UTC
on stored session universe is different (if sliders were used to filter genesets in the original anlaysis) which changes the p-values.

In original session all genesets in the initial created EM are used to calculate genes in the universe (even if some have been filtered out) In restored session on genesets present in the map are used making the universe smaller, making the p-values larger.

Will be resolved once universe parameter is calculated on load and stored with session separately.

**Comment by mikekucera** [comment] 2015-04-20 15:08
Duplicate of #3

**Closed as completed by mikekucera** 2015-04-20 15:08 UTC
Labels: bug, enhancement, PostAnalaysis
