### ISSUE TITLE
different filters/thresholds for different datasets

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#119] opened 2015-07-31 15:55 UTC
When creating an EM from different data sets (potentially from two different platforms) you might want to filter each dataset by a different p-value and q-value threshold (because of differing number of genes in the set or data quality).

In the meantime you can create an EM with one threshold and then filter the nodes using selection.  Select nodes with a p-value and q-value higher than your second threshold and delete them from the network.

**Comment by mikekucera** [comment] 2017-10-19 18:45
Duplicate of #245

**Closed as completed by mikekucera** 2017-10-19 18:45 UTC
Labels: duplicate, enhancement
