### ISSUE TITLE
on windows p-value/qvalue option on slider is not showing up

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#239] opened 2017-07-06 15:41 UTC
Using a windows surface with EM RC1 the slider show no p-value/qvalue option.  Default to p-value.

**Comment by risserlin** [comment] 2017-07-06 15:43
Found with working with Chi

**Comment by mikekucera** [comment] 2017-10-19 18:47
Duplicate of #279

**Closed as completed by mikekucera** 2017-10-19 18:47 UTC
Labels: bug, duplicate
