### ISSUE TITLE
3.1 RC1  heatmap leading edge: would like to see the leading edge genes before the "grey" genes

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#300] opened 2018-01-17 16:32 UTC
3.1 RC1  heatmap leading edge:  I would like to see the leading edge genes before the "grey" genes
see picture (automatically sort the grey genes at the bottom whether the sort is ascending or descending) 
![screen shot 2018-01-17 at 11 27 28 am](https://user-images.githubusercontent.com/7570379/35054162-ee3abebe-fb79-11e7-9837-7cd64a2b6693.png)

**Comment by mikekucera** [comment] 2018-01-18 15:28
This is a duplicate of #250.

Unfortunately changing the sorting behavior is very difficult because it is private to the JTable class.

**Closed as completed by mikekucera** 2018-01-18 15:28 UTC
Labels: enhancement
