### ISSUE TITLE
GREAT with multiple datasets: only 1 node table column containing gene set size

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/EnrichmentMapApp#444] opened 2021-01-08 20:56 UTC
I have created an enrichment map with 9 datasets without a gmt file (as great does not provide one). 
An important information to analyze the map is to compare the number of genes present in each node for the different conditions but only one column describing the gene-set size is present in the node table. I'm assuming that it represents dataset 1 . It would have been very useful for me to get this information for each condition ( geneset size columns)  to use it in some filtering strategies and node prioritization.

**Comment by mikekucera** [comment] 2021-01-13 14:31
I believe the gs_size column contains the size of the unioned set of all the gene sets with that name.

**Comment by mikekucera** [comment] 2022-11-08 14:59
gs_size columns per dataset?

**Comment by veroniquevoisin** [comment] 2022-11-09 16:02
I'm realizing that this is the same as a recent comment I made. If the total observed column is taken from GREAT, then it will be the same for all the samples (don't need to do the union) and will represent the original gene set size (as gs_size in GSEA) and this is what I would in recommend. Then, if possible only, it would be for sure helpful to get also the overlapping gs_size for each of the sample that is in the observed column of the GREAT result, one for each sample: overlap_gs_size1, overlap_gs_size2, etc...

**Comment by mikekucera** [comment] 2022-11-22 18:36
Duplicate of #495

**Closed as completed by mikekucera** 2022-11-22 18:36 UTC
Labels: enhancement
