### ISSUE TITLE
Problem for heat map

### ISSUE THREAD

**Issue by crysrain** [BaderLab/EnrichmentMapApp#176] opened 2017-02-27 22:15 UTC
Hi,

Does the function of heat map still work? I used heat map before and worked. Now it did not work even if I tested it by my old data.

**Comment by risserlin** [comment] 2017-02-28 15:18
What version of cytoscape and enrichment map are you using?  The heatmap should work but someone yesterday just told that they were also having issues with the heatmap.  Do you have the latest version of Enrichment map (2.2.0) that was released in Jan 2017?

**Comment by crysrain** [comment] 2017-02-28 15:39
Hi,

I used the newest version of cytoscap and Enrichment map.

**Comment by risserlin** [comment] 2017-02-28 15:51
Are there any error messages coming up in the command window?  Do you have a session file that is having this issue that you can send us?  I can't recreate it with any of my sessions.

**Comment by crysrain** [comment] 2017-02-28 22:08
[chart_51ED3C7AD97B1484253374433_2C2T_up.txt](https://github.com/BaderLab/EnrichmentMapApp/files/809091/chart_51ED3C7AD97B1484253374433_2C2T_up.txt)
There is error message.

**Comment by risserlin** [comment] 2017-03-01 01:09
the attached file looks more like an input file as opposed to an error message.

**Comment by crysrain** [comment] 2017-03-01 16:37
Sorry. What is the session file?

**Comment by risserlin** [comment] 2017-03-01 16:40
in cytoscape:
File -> "save as" will generate a cytoscape session file.

**Comment by crysrain** [comment] 2017-03-01 16:45
How can I upload it? I got the information that " We don't support that file type."

**Comment by risserlin** [comment] 2017-03-01 16:47
you can email it to me. (ruth dot isserlin at utoronto dot ca)

**Comment by risserlin** [comment] 2017-03-01 18:13
You are trying to build your enrichment map with the wrong david output file.  You are getting the first link "functional Annotation clustering" file when you should be getting "functional Annotation chart"

screenshot of output file to get on david interface:  http://www.baderlab.org/WhereToGetDavidChart

The file you are giving enrichment map doesn't list the genes so the expression viewer doesn't have anything to create.

**Comment by crysrain** [comment] 2017-03-02 17:17
Thanks for your help. I think there is no problem for the enrichment map. When I input David file into enrichments for generating heatmap, I only got one column of Dummy expression (Heatmap 1). However, when I also input expression data, I got the real heatmap output (Heatmap 2). Are you familiar  with RNAseq data analysis by using Tophat, cuffmerge, cufflink, and cuffdiff? From cuffdiff output files, I only get the means of 3 repeats. Do you know how or where I can get the individual value of my each sample?
![heatmap 1](https://cloud.githubusercontent.com/assets/8159227/23518633/bb3267ac-ff39-11e6-859f-5ba84d46bffe.png)
![heatmap 2](https://cloud.githubusercontent.com/assets/8159227/23518634/bed92f1c-ff39-11e6-9155-09dbf428974b.png)

**Comment by crysrain** [comment] 2017-03-08 06:44
Hi,


I am so sorry to bother you again. It should be easy to remove labels as you mentioned before. However, I cannot remove them by using the method you provided. Could you please help me to solve this problem?


Best,


Jian

________________________________

**Comment by risserlin** [comment] 2017-03-08 14:22
HI Jian, 
I was able to reproduce this.  It looks like a bug.  When you delete the labels it isn't refreshing the style.  As a work around right now you can get around this bug as follows:

delete the labels 
Edit -> Remove Mapping from selected visual properties

Change the Style:
Change the style from EM1_Enrichment_map_style to default
and then 
Change back from default to EM1_Enrichment_map_style

That should force the style to get refreshed and labels should be removed.  

I am not sure if this is cytoscape issue or enrichment map issue. 

Thanks, 
Ruth

**Comment by crysrain** [comment] 2017-03-10 22:13
Hi,


Thanks for help me to solve this problem.

Based on "EM1_Enrichment_map_style", what's the meaning of the size of nodes?

________________________________

**Comment by crysrain** [comment] 2017-03-10 22:23
Hi Ruth,


Sorry I forgot to attach the image.  I input 2 datasets with gene expression files and DAVID output files. There are tow colors for edges. What's the meaning of purple and green colors?


Best,


Jian

________________________________

**Comment by risserlin** [comment] 2017-03-15 14:26
Hi Jian, 
the size of the nodes is reflective of the numbers of genes associated with the geneset.

The two different color edges reflect the fact that you have a different set of genes associated with dataset1 and dataset2.  Because there are different universes of genes in dataset1 and dataset2 the overlaps are calculated separately.  Dataset1 overlaps are represented as a green edge and dataset 2 overlaps are represented in blue.  

There is some additional explanation here:
http://baderlab.org/Software/EnrichmentMap/DavidTutorial

**Comment by crysrain** [comment] 2017-03-15 15:07
Hi Ruth,


This is what I expect for the size of the node. However, when I looked at the number of genes I found they are quite different between nodes with similar size. In the enrichment map, nodes within the upper right group actually contain 2 genes but the size of the node much larger than others that even contain more than 20 genes. That's the reason I asked the meaning of the size of the node.

________________________________

**Comment by risserlin** [comment] 2017-03-15 15:22
Are you comparing nodes sizes between two datasets?  Can you put the image of the specific example here?
dataset1 determines the size of the node and dataset2 determines the thickness of the border.  It is mapped as a continuous mapper so it is based on a gradient whose upper and lower bounds are dependent on your data.  If you want to make it consistent you can manually adjust it in the style manager.  In the below screen shot my range is 10 genes to 474 genes in a geneset mapped to the range of size 20 to 65.
![screen shot 2017-03-15 at 11 18 36 am](https://cloud.githubusercontent.com/assets/3842763/23955903/a0ebedf4-0971-11e7-8949-d2623b18b139.png)

**Closed as completed** 2017-05-10 15:13 UTC
